version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  mongodb_test:
    image: mongo:latest
    command: ["mongod", "--storageEngine", "ephemeralForTest"]
    ports:
      - 27018:27017
volumes:
  mongo_data:

